### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by chrisribal** [shopwareLabs/SwagMediaS3#15]
Our media folder has a size of about 50 GB. When calling the migration service with

`php -f bin/console sw:media:migrate --from=local --to=s3`

the script aborts after about 10 seconds with:

> Allowed memory size of 4294967296 bytes exhausted

What can we do to migrate our media folder to s3?

EDIT: as you can see, currently i've set the PHP memory_limit to 4 GB

**Comment by janbuecker** [comment]
What Shopware version do you use for migrating to S3?

**Comment by chrisribal** [comment]
We're using 5.2.22.
In the meantime we got the migration service running - we had to increase our memory_limit in the runtime to 16 GB. Apparently the service needs that space for us.
As i could see the migration scripts load a list of all media files to migrate - which in our case are millions of files. Maybe there is better solution, like batch uploading or so?

**Comment by janbuecker** [comment]
Of course there is. We've updated the scripts to process the files one after another instead of processing all at once. The updated version will be published with 5.3.

In case you need the change now, you can backport it from [here](https://github.com/shopware/shopware/blob/5.3/engine/Shopware/Bundle/MediaBundle/MediaMigration.php).

I think that the error is core related rather than the S3 adapter. Therefore I'll close this issue.

Thanks for the report @chrisribal.
